### ISSUE TITLE
QtMessageHandler dereferences null pointer in release builds

### ISSUE THREAD

**Issue by zaCade** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#139]
I've at this point tried to actually update to 3.0, since the feature i requested before is claimed to be implemented in it, but i've ran into the problem that no matter what i do. It simply wont show up in steamvr, also starting the executable manually doesnt work, since it crashes after like a few seconds.

**Comment by ykeara** [comment]
Need Log from OVRAS.

For 3.0.0 = %appData%/AdvancedSettings-Team/AdvancedSettings.txt

Log for VRserver might also be helpful (In steam install directory)

also try to launch AdvancedSettings.exe with "--force-install-manifest" [it will not stay running after running this command, but SHOULD set it to auto play if that is the issue]

**Comment by zaCade** [comment]
Here are the files you asked for, before and after running the command. However after running the command i seem to not have gotten a advancedsettings log file anymore.

[Before_vrserver.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3024768/Before_vrserver.txt)
[After_vrserver.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3024769/After_vrserver.txt)
[Before_AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3024770/Before_AdvancedSettings.log)

**Comment by ykeara** [comment]
did you try just running steamVR after forcing install the manifest? does advanced settings show up in task-manager while steamvr is running?

**Comment by zaCade** [comment]
It does show up for like 10 seconds, after that it disapears again. I'm guessing it crashes or something, but no idea whats happening exactly, since the logs dont seem to tell me anything altrough this time it complaints about not finding the overlay?
[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3024894/AdvancedSettings.log)

**Comment by zaCade** [comment]
I find this really odd, because when i run the 2.7 version (or below, im not sure if below works still). It all functions like it should, this strange behavior only happens with 2.8 and above.

**Comment by username223** [comment]
What happens if you directly launch the `AdvancedSettings.exe` file in the install directory without SteamVR running?

**Comment by username223** [comment]
Also, could you see if there are any crash dumps in `%LOCALAPPDATA%/CrashDumps`?

**Comment by zaCade** [comment]
Starting it without SteamVR running does start SteamVR, but it also seems to crash again after like 10 seconds, like before. However i also checked for the crash dumps, i've attached those in a zip.
[CrashDumps.zip](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3025423/CrashDumps.zip)
[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3025424/AdvancedSettings.log)

**Comment by username223** [comment]
Crash dumps show a null pointer exception `Unhandled exception at 0x000000013F8636C5 (AdvancedSettings.exe) in AdvancedSettings.exe.1432.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.`.

`Unhandled exception at 0x000000013FE728B3 (AdvancedSettings.exe) in AdvancedSettings.exe.17476.dmp: 0xC0000005: Access violation reading location 0x0000000000000000.`

Might be the same issue as #130.

@zaCade could you download the debug build [here](http://s000.tinyupload.com/index.php?file_id=90271911083812185244), run it and then upload the resulting crash dump?

Also, what are your specs (in as much detail as possible, OS, CPU, RAM, etc.).

**Comment by zaCade** [comment]
Running that debug build you send, gives me a error about a missing ucrtbased.dll on my computer.
This time i've gotten no crashdump.

Specs are as followed
OS: Windows 7 Professional SP1
CPU: Intel i7-6700K @ 4.00GHz
RAM: Corsair Vengeance LPX 16GB
GPU: Asus Rog Strix RX580 8G Gaming
Motherboard: MSI-Z270-Gaming-M5

Altrough i doubt my specs could be the cause here, since version 2.7 runs entirely fine,
could it however be related that ive installed OVRAS inside the steamvr folder?
Altrough for 2.7 that wasn't an issue.

**Comment by username223** [comment]
Either download and install Visual Studio 2017 or download [this](http://s000.tinyupload.com/index.php?file_id=08425759883301371182) and put it in the same folder as the AdvancedSettings binary.

**Comment by zaCade** [comment]
Alright, no idea what you changed in the debug build. But it seems to be working now.

**Comment by username223** [comment]
There's nothing different about the debug build other than that it's compiled without optimizations.

Most likely we've got some undefined behavior somewhere that only appears with optimizations and only on yours and #130 	machines.

What is your setup like in terms of HMD, controllers, audio devices, keyboards, OS language, keyboard layout?

**Comment by zaCade** [comment]
Setup:
- Vive
- Vive Regular Controllers
- Steelseries Siberia 200 (not 100% sure here, its a 3.5mm jack one though)
- Corsair K70 RGB
- Dutch Language
- US International Layout

**Comment by username223** [comment]
@zaCade 
Could you try [this](https://ufile.io/ociqx) version and then uploading the crashdump?

It's the release build with debug symbols enabled, should allow me to figure out where we have a null pointer dereference.

**Comment by zaCade** [comment]
Here you go.
[AdvancedSettings.exe.11708.dmp.zip](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3026042/AdvancedSettings.exe.11708.dmp.zip)

**Comment by username223** [comment]
@zaCade Thanks.

The release build with debug symbols enabled showed that ironically the crash is the result of the QtMessageHandler trying to report a warning. I've added a extra checks and logging calls to the QtMessageHandler in an attempt to figure out why you're the only ones suffering from this bug and why Qt would give a null pointer for a message.

Please run and upload crashdump of [this](https://ufile.io/gotd4) build.

**Comment by zaCade** [comment]
I see that the log is complaining about a missing font. Maybe thats it?
[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3026399/AdvancedSettings.log)
[AdvancedSettings.exe.22340.dmp.zip](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3026397/AdvancedSettings.exe.22340.dmp.zip)

**Comment by username223** [comment]
@zaCade 
The root issue is that you're missing some font stuff. I have no idea what it is. Most likely it'll be fixed by updating Windows.

The actual crash is because the `QMessageLogContext` class doesn't record `file` and `line` attributes on release builds, which passes null pointers to the logging functions.

Please try [this](https://ufile.io/79426) build. This build should not crash on you, only report the errors that previously caused the crash. Please check if everything works as expected and then upload logs. If it crashes then I would also like a crash dump.

Thank you for being so speedy, it's been very helpful in establishing the causes. :)

**Comment by zaCade** [comment]
I'm afraid it still crashes, but what makes me wonder trough, has some font stuff been changed since 2.7 then? Since that build/release functioned just fine for me.

[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3026464/AdvancedSettings.log)
[AdvancedSettings.exe.21384.dmp.zip](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3026463/AdvancedSettings.exe.21384.dmp.zip)

**Comment by zaCade** [comment]
Something, i could possibly think off if thats the case. Maybe add in some 'fallback' fonts, that it uses incase it can't find the right ones? Just my mind trying to help think of 'solutions'. As for being quick with responses the same could be said about the OVRAS team in this case, i mean, my issue got a response within an hour. Thats quite impressive if you ask me.

**Comment by username223** [comment]
I don't think the missing fonts itself are a big deal. They're only a warning. The problem is our logging handler crashes because it doesn't have enough information.

[This](https://ufile.io/ac7ku) build should not crash.

You know the drill, test, logs, dumps. :)

**Comment by zaCade** [comment]
Indeed, no crash. Therefor no dump, but here is the log.
[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3026495/AdvancedSettings.log)

**Comment by username223** [comment]
@zaCade 
Did the actual features of the app work?

**Comment by zaCade** [comment]
Yeah, i was able to open it in SteamVR. Didnt test much further then that.

**Comment by username223** [comment]
Alright, then I would consider this issue fixed.

The `Unable to open default EUDC font: "C:\\Windows\\FONTS\\EUDC.TTE"` issue is on your end, so there's nothing we can do about it.

Since it's only a warning it's probably not going to cause any issues.

It is likely (almost definitely) Qt trying to pull in stuff it needs. The 2.7.0 release was not built on our CI (Continuous Integration) server, so there's really no way to know if we had a slightly different version of something.

The next release (3.1.0) will have this issue fixed, in the meantime you can use [this](https://uploadfiles.io/ac7ku) (same as before, recapping for potential third party viewers) build.

This issue will be closed when the PR that fixes it is pushed to master.

___

The `mainQtMessageHandler` function uses the `QMessageLogContext` `file` and `line` members, which are not available on release builds causing them to dereference a null pointer. The [official docs](https://doc.qt.io/qt-5/qmessagelogcontext.html) say that you can set `QT_MESSAGELOGCONTEXT` in order to also have the functionality in release builds, but this does not work.

Adding `CONFIG   += c++1z force_debug_info` creates a release build with debug symbols, which means that the call stack is more easily analyzed. Opening the dump file in the directory of the binary and `.pdb` file shows symbols. The binary must be the exact same. Recompiling is not good enough due to non-reproducible builds.

Removing the `file` and `line` uses fixes the issue.
